name: Update

on:
    push:
        branches:
            - main
    workflow_dispatch:
 
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Deployment:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            channel: 'latest'